services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 main:app
    envVars:
      - key: PORT
        value: 10000