services:
  - type: web
    name: fastapi-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PORT
        value: 10000